import React, { useState } from 'react'
import yol1Logo from './assets/yol1-logo.svg'
import yol1Mark from './assets/yol1-mark.svg'
import {
  Activity, AlertCircle, ArrowDownLeft, ArrowRight, ArrowUpRight, BarChart3,
  Bell, Building2, Check, CheckCircle2, ChevronDown, ChevronRight, CircleDollarSign,
  ClipboardCheck, CreditCard, Download, FileBarChart, Filter, GitBranch, Landmark,
  Layers3, LayoutDashboard, Link2, ListFilter, LockKeyhole, Menu, MoreHorizontal,
  Plus, ReceiptText, Search, Settings, ShieldCheck, Sparkles, Users, WalletCards,
  X, Zap
} from 'lucide-react'
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis
} from 'recharts'

const money = value => `$${Number(value).toLocaleString('es-CL')}`
const chartData = [
  { name: 'Ene', entradas: 590, salidas: 370 }, { name: 'Feb', entradas: 650, salidas: 430 },
  { name: 'Mar', entradas: 720, salidas: 510 }, { name: 'Abr', entradas: 680, salidas: 470 },
  { name: 'May', entradas: 810, salidas: 590 }, { name: 'Jun', entradas: 890, salidas: 640 },
]
const accounts = [
  { name: 'Juan Pérez', id: 'CV-10021', type: 'Usuario final', balance: 185400, status: 'Activa', activity: 'Hace 4 min' },
  { name: 'Camila Rojas', id: 'CV-10022', type: 'Usuario final', balance: 92100, status: 'Activa', activity: 'Hace 12 min' },
  { name: 'Diego Morales', id: 'CV-10023', type: 'Usuario final', balance: 340800, status: 'Pendiente revisión', activity: 'Hace 18 min' },
  { name: 'Sofía Castillo', id: 'CV-10024', type: 'Usuario final', balance: 56700, status: 'Activa', activity: 'Hace 26 min' },
  { name: 'Martín Silva', id: 'CV-10025', type: 'Usuario final', balance: 720000, status: 'Activa', activity: 'Hace 35 min' },
  { name: 'Retiros Pendientes', id: 'CV-OPS-01', type: 'Operativa', balance: 128900000, status: 'Activa', activity: 'Hace 2 min' },
  { name: 'Recaudación Tarjetas', id: 'CV-OPS-02', type: 'Recaudación', balance: 274500000, status: 'Activa', activity: 'Hace 1 min' },
  { name: 'Conciliación Diaria', id: 'CV-OPS-03', type: 'Conciliación', balance: 38200000, status: 'Activa', activity: 'Hace 8 min' },
  { name: 'Proveedores Operacionales', id: 'CV-OPS-04', type: 'Proveedores', balance: 64800000, status: 'Activa', activity: 'Ayer' },
]
const users = [
  { name: 'Juan Pérez', id: 'USR-10021', account: 'CV Usuario Juan Pérez', available: 185400, held: 0, state: 'Retiro pendiente', last: 'Retiro solicitado', alert: 'Retiro pendiente' },
  { name: 'Camila Rojas', id: 'USR-10022', account: 'CV Usuario Camila Rojas', available: 92100, held: 0, state: 'Activa', last: 'Abono recibido', alert: 'Sin alertas' },
  { name: 'Diego Morales', id: 'USR-10023', account: 'CV Usuario Diego Morales', available: 340800, held: 120000, state: 'Pendiente revisión', last: 'Movimiento retenido', alert: 'Saldo retenido' },
  { name: 'Sofía Castillo', id: 'USR-10024', account: 'CV Usuario Sofía Castillo', available: 56700, held: 0, state: 'Activa', last: 'Retiro ejecutado', alert: 'Sin alertas' },
  { name: 'Martín Silva', id: 'USR-10025', account: 'CV Usuario Martín Silva', available: 720000, held: 0, state: 'Activa', last: 'Abono recibido', alert: 'Sin alertas' },
]
const movements = [
  { date: 'Hoy, 10:42', user: 'Juan Pérez', account: 'CV-10021', type: 'Abono recibido', amount: 185400, status: 'Completado', id: 'OP-948201' },
  { date: 'Hoy, 10:38', user: 'Juan Pérez', account: 'CV-10021', type: 'Retiro solicitado', amount: -185400, status: 'Pendiente', id: 'OP-948199' },
  { date: 'Hoy, 10:21', user: 'Sofía Castillo', account: 'CV-10024', type: 'Retiro ejecutado', amount: -56700, status: 'Completado', id: 'OP-948183' },
  { date: 'Hoy, 09:58', user: 'Camila Rojas', account: 'CV-10022', type: 'Transferencia interna', amount: 92100, status: 'Completado', id: 'OP-948174' },
  { date: 'Hoy, 09:44', user: 'Operación interna', account: 'CV-OPS-02', type: 'Comisión ProntoPaga', amount: -128000, status: 'Completado', id: 'OP-948166' },
  { date: 'Hoy, 09:31', user: 'Diego Morales', account: 'CV-10023', type: 'Movimiento retenido', amount: 120000, status: 'En revisión', id: 'OP-948151' },
]
const nav = [
  ['Vista general', LayoutDashboard], ['Cuentas virtuales', Layers3], ['Usuarios finales', Users],
  ['Movimientos', Activity], ['Retiros y pagos', CircleDollarSign], ['Conciliación', ClipboardCheck],
  ['Tarjetas', CreditCard], ['Reportes', BarChart3], ['Usuarios y permisos', ShieldCheck],
  ['Integraciones', Link2], ['Configuración', Settings],
]

function StatusBadge({ children }) {
  const text = String(children)
  const tone = /Activa|Completado|Conectado|Conciliado|Aprobado|Ejecutado|Sin alertas/.test(text) ? 'success'
    : /Pendiente|revisión|Revisión|Retiro|Próximamente|Futura/.test(text) ? 'warning'
    : /Rechazado|Bloqueada|retenido|alerta|Alerta/.test(text) ? 'danger' : 'neutral'
  return <span className={`badge ${tone}`}><span />{text}</span>
}
function Avatar({ name, small = false }) {
  return <span className={`avatar ${small ? 'small' : ''}`}>{name.split(' ').map(x => x[0]).slice(0, 2).join('')}</span>
}
function Button({ children, icon: Icon, secondary = false, ghost = false, onClick, className = '' }) {
  return <button className={`button ${secondary ? 'secondary' : ''} ${ghost ? 'ghost' : ''} ${className}`} onClick={onClick}>{Icon && <Icon size={16} />}{children}</button>
}
function MetricCard({ label, value, icon: Icon, detail, tone = 'green' }) {
  return <div className="metric-card">
    <div className={`metric-icon ${tone}`}><Icon size={18} /></div>
    <div className="metric-label">{label}</div><div className="metric-value">{value}</div>
    <div className="metric-detail">{detail}</div>
  </div>
}
function PageTitle({ eyebrow, title, subtitle, actions }) {
  return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{actions && <div className="page-actions">{actions}</div>}</div>
}
function Card({ title, subtitle, action, children, className = '' }) {
  return <section className={`card ${className}`}><div className="card-head"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>
}
function DataTable({ headers, children }) {
  return <div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>
}
function SearchFilters({ account = false }) {
  return <div className="filters"><div className="filter-search"><Search size={16} /><input placeholder={account ? 'Buscar por nombre o ID de cuenta...' : 'Buscar en esta vista...'} /></div><button><ListFilter size={15} /> Estado <ChevronDown size={14} /></button><button><Filter size={15} /> Tipo <ChevronDown size={14} /></button><button>Última actividad <ChevronDown size={14} /></button></div>
}
function Timeline({ compact = false }) {
  const steps = ['Fondos recibidos', 'Asignado a cuenta virtual', 'Retiro solicitado', 'Aprobación pendiente', 'Pago ejecutado', 'Conciliado']
  return <div className={`timeline ${compact ? 'compact' : ''}`}>{steps.map((s, i) => <div className={`timeline-step ${i < 3 ? 'done' : i === 3 ? 'current' : ''}`} key={s}><span>{i < 3 ? <Check size={13} /> : i + 1}</span><div><strong>{s}</strong>{!compact && <small>{i < 3 ? 'Completado' : i === 3 ? 'En curso' : 'Pendiente'}</small>}</div>{i < steps.length - 1 && <i />}</div>)}</div>
}
function Modal({ type, onClose, onConfirm }) {
  const title = type === 'create' ? 'Crear cuenta virtual' : type === 'trace' ? 'Trazabilidad de operación' : type === 'withdraw' ? 'Aprobar retiro' : 'Crear tarjeta'
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}>
    <div className="modal-head"><div><span className="eyebrow">Yol1 Business</span><h2>{title}</h2></div><button onClick={onClose}><X size={20} /></button></div>
    {type === 'create' && <div className="form-grid"><label>Nombre de cuenta<input placeholder="Ej. CV Proyecto Norte" /></label><label>Tipo de cuenta<select><option>Usuario final</option><option>Operativa</option><option>Proyecto</option></select></label><label>Moneda<select><option>CLP</option><option>USD</option><option>EUR</option></select></label><label>Usuario o proyecto asociado<input placeholder="Buscar usuario o proyecto" /></label><label className="wide">Estado inicial<select><option>Activa</option><option>Pendiente revisión</option></select></label></div>}
    {type === 'trace' && <><div className="trace-summary"><div><small>Usuario</small><strong>Juan Pérez</strong><span>USR-10021</span></div><div><small>Cuenta virtual</small><strong>CV Usuario · Juan Pérez</strong><span>CV-10021</span></div><div><small>Monto</small><strong>$185.400</strong><StatusBadge>Retiro pendiente</StatusBadge></div></div><Timeline /></>}
    {type === 'withdraw' && <div className="confirm-box"><div className="confirm-icon"><CheckCircle2 size={25} /></div><h3>¿Aprobar retiro por $185.400?</h3><p>Esta es una acción visual de demo. No ejecuta pagos reales.</p><div className="detail-list"><span>Usuario <b>Juan Pérez</b></span><span>Cuenta origen <b>CV-10021</b></span><span>Destino <b>Banco ficticio ···· 4192</b></span></div></div>}
    {type === 'card' && <div className="confirm-box"><div className="confirm-icon"><CreditCard size={25} /></div><h3>Nueva tarjeta sobre cuenta virtual</h3><p>Demo conceptual. Las tarjetas serán una capa futura sobre cuentas virtuales.</p></div>}
    <div className="modal-footer"><Button secondary onClick={onClose}>Cancelar</Button><Button onClick={() => { onConfirm?.(); onClose() }}>{type === 'trace' ? 'Cerrar' : type === 'withdraw' ? 'Aprobar retiro' : 'Crear'}</Button></div>
  </div></div>
}

function Overview({ open, navigate }) {
  return <><PageTitle eyebrow="Miércoles, 10 de junio" title="Hola, Benja" subtitle="Tu plata, ordenada. Tu operación, visible." actions={<><Button secondary icon={Download}>Reporte</Button><Button icon={Plus} onClick={() => open('create')}>Crear cuenta virtual</Button></>} />
    <div className="hero-balance"><div><span className="eyebrow light">Cuenta madre · CLP</span><h2>$845.320.000</h2><p><span className="live-dot" /> Balance total disponible</p></div><div className="hero-stats"><div><span>Entradas hoy</span><b>+$184.300.000</b></div><div><span>Salidas hoy</span><b>−$96.700.000</b></div><div><span>Variación</span><b>+8,4%</b></div></div><img className="hero-brand-mark" src={yol1Mark} alt="" /></div>
    <div className="quick-actions"><button onClick={() => open('create')}><Plus /><span>Crear cuenta virtual</span><small>Nueva subcuenta</small></button><button onClick={() => navigate('Usuarios finales')}><Users /><span>Asignar a usuario</span><small>Vincular identidad</small></button><button onClick={() => open('withdraw')}><CheckCircle2 /><span>Aprobar retiro</span><small>4 pendientes</small></button><button onClick={() => navigate('Conciliación')}><ClipboardCheck /><span>Ver conciliación</span><small>Cierre diario</small></button></div>
    <div className="metric-grid"><MetricCard label="Cuentas virtuales activas" value="18.420" icon={Layers3} detail="+182 este mes" /><MetricCard label="Recaudación hoy" value="$184,3M" icon={ArrowDownLeft} detail="+12,5% vs. ayer" /><MetricCard label="Retiros pendientes" value="$42,6M" icon={ArrowUpRight} detail="4 requieren aprobación" tone="amber" /><MetricCard label="Pendiente por conciliar" value="$4,8M" icon={ClipboardCheck} detail="98,2% conciliado" tone="blue" /><MetricCard label="Alertas operativas" value="12" icon={AlertCircle} detail="3 de alta prioridad" tone="red" /></div>
    <div className="two-col wide-left"><Card title="Entradas vs. salidas" subtitle="Flujo mensual · MM CLP" action={<button className="text-action">Últimos 6 meses <ChevronDown size={14} /></button>}><div className="chart"><ResponsiveContainer><AreaChart data={chartData}><defs><linearGradient id="g1" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#80EF0C" stopOpacity=".42"/><stop offset="100%" stopColor="#80EF0C" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#e5e2d8" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="entradas" stroke="#80EF0C" fill="url(#g1)" strokeWidth={2.5}/><Area dataKey="salidas" stroke="#112E3C" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card>
    <Card title="Salud operativa" subtitle="Estado de la operación hoy"><div className="health-score"><div className="score-ring"><b>94</b><span>/100</span></div><div><strong>Operación saludable</strong><p>La cuenta madre y sus cuentas virtuales están operando dentro de los parámetros definidos.</p></div></div><div className="health-bars"><span><b>Asignación de fondos</b><i><em style={{width:'98%'}} /></i><small>98%</small></span><span><b>Conciliación diaria</b><i><em style={{width:'94%'}} /></i><small>94%</small></span><span><b>Retiros procesados</b><i><em style={{width:'91%'}} /></i><small>91%</small></span></div></Card></div>
    <Card title="Últimas transacciones" subtitle="Actividad consolidada de la cuenta madre y cuentas virtuales" action={<button className="text-action" onClick={() => navigate('Movimientos')}>Ver todos <ArrowRight size={14}/></button>}><MovementTable rows={movements.slice(0,4)} /></Card>
    <div className="concept-note"><Sparkles size={20}/><div><strong>Una cuenta madre. Miles de operaciones trazables.</strong><p>Yol1 Business permite operar una cuenta madre y crear cuentas virtuales por usuario final, proyecto o flujo, con control de saldos, trazabilidad, conciliación y pagos desde una sola plataforma.</p></div></div>
  </>
}
function MovementTable({ rows = movements }) {
  return <DataTable headers={['Fecha', 'Usuario / origen', 'Cuenta virtual', 'Movimiento', 'Monto', 'Estado', 'ID operación']} >{rows.map(m => <tr key={m.id}><td className="muted">{m.date}</td><td><div className="person"><Avatar name={m.user} small/><b>{m.user}</b></div></td><td><code>{m.account}</code></td><td>{m.type}</td><td className={m.amount > 0 ? 'positive' : 'negative'}><b>{m.amount > 0 ? '+' : '−'}{money(Math.abs(m.amount))}</b></td><td><StatusBadge>{m.status}</StatusBadge></td><td className="muted">{m.id}</td></tr>)}</DataTable>
}
function VirtualAccounts({ open }) {
  return <><PageTitle eyebrow="Producto central" title="Cuentas virtuales" subtitle="Administra los fondos de cada usuario y flujo operativo desde una cuenta madre." actions={<><Button secondary icon={Download}>Exportar saldos</Button><Button icon={Plus} onClick={() => open('create')}>Crear cuenta virtual</Button></>} />
    <div className="mother-account"><div className="mother-top"><div className="mother-logo"><Building2/></div><div><span className="eyebrow light">Cuenta madre</span><h2>ArenaPlay Demo SpA</h2><p>RUT 76.555.123-9 · Banco BICE · CLP</p></div><StatusBadge>Activa</StatusBadge></div><div className="mother-balance"><span>Balance consolidado</span><strong>$845.320.000</strong><small>18.420 cuentas virtuales activas</small></div><div className="mother-actions"><Button secondary icon={Users}>Asignar a usuario</Button><Button secondary icon={GitBranch} onClick={() => open('trace')}>Ver trazabilidad</Button></div></div>
    <div className="account-flow"><div className="flow-root"><Landmark/><span>Cuenta madre</span><b>$845,3M</b></div><ChevronRight/><div className="flow-group"><Users/><span>Usuarios finales</span><b>18.415 cuentas</b></div><div className="flow-group"><WalletCards/><span>Operación interna</span><b>5 cuentas</b></div><ChevronRight/><div className="flow-group"><Activity/><span>Movimientos</span><b>32.890 hoy</b></div><div className="flow-group"><ClipboardCheck/><span>Conciliación</span><b>98,2%</b></div></div>
    <div className="metric-grid four"><MetricCard label="Balance usuarios finales" value="$339,7M" icon={Users} detail="40,2% del total" /><MetricCard label="Balance cuentas operativas" value="$506,8M" icon={Building2} detail="59,8% del total" tone="blue" /><MetricCard label="Saldos retenidos" value="$1,2M" icon={LockKeyhole} detail="8 cuentas en revisión" tone="amber" /><MetricCard label="Actividad hoy" value="32.890" icon={Activity} detail="+18,2% vs. promedio" /></div>
    <Card title="Directorio de cuentas virtuales" subtitle="Saldos y actividad en tiempo real"><SearchFilters account/><DataTable headers={['Cuenta virtual', 'ID cuenta', 'Tipo', 'Saldo disponible', 'Estado', 'Última actividad', '']} >{accounts.map(a => <tr key={a.id}><td><div className="person"><Avatar name={a.name} small/><b>{a.name}</b></div></td><td><code>{a.id}</code></td><td>{a.type}</td><td><b>{money(a.balance)}</b></td><td><StatusBadge>{a.status}</StatusBadge></td><td className="muted">{a.activity}</td><td><button className="more" onClick={() => open('trace')}><MoreHorizontal size={18}/></button></td></tr>)}</DataTable></Card>
  </>
}
function UsersView({ open }) {
  return <><PageTitle eyebrow="Identidades vinculadas" title="Usuarios finales" subtitle="Cada usuario tiene su propia cuenta virtual, saldo y trazabilidad." actions={<><Button secondary icon={Download}>Exportar historial</Button><Button icon={Users}>Asignar cuenta</Button></>} /><div className="metric-grid four"><MetricCard label="Usuarios con cuenta activa" value="18.420" icon={Users} detail="99,4% del total"/><MetricCard label="Saldo total usuarios" value="$339,7M" icon={WalletCards} detail="$18.441 promedio"/><MetricCard label="Saldo retenido" value="$1,2M" icon={LockKeyhole} detail="8 cuentas afectadas" tone="amber"/><MetricCard label="Alertas abiertas" value="12" icon={AlertCircle} detail="3 alta prioridad" tone="red"/></div>
  <Card title="Directorio de usuarios" subtitle="Vista unificada de identidad, cuenta virtual y riesgo"><SearchFilters/><DataTable headers={['Usuario final','Cuenta virtual asociada','Disponible','Retenido','Estado','Último movimiento','Riesgo / alerta','']} >{users.map(u=><tr key={u.id}><td><div className="person"><Avatar name={u.name} small/><span><b>{u.name}</b><small>{u.id}</small></span></div></td><td>{u.account}</td><td><b>{money(u.available)}</b></td><td>{money(u.held)}</td><td><StatusBadge>{u.state}</StatusBadge></td><td>{u.last}</td><td><StatusBadge>{u.alert}</StatusBadge></td><td><button className="more" onClick={()=>open('trace')}><MoreHorizontal size={18}/></button></td></tr>)}</DataTable></Card></>
}
function MovementsView({ open }) { return <><PageTitle eyebrow="Ledger operativo" title="Movimientos" subtitle="Todas las entradas, salidas y transferencias internas con trazabilidad completa." actions={<><Button secondary icon={Download}>Exportar</Button><Button icon={GitBranch} onClick={()=>open('trace')}>Ver trazabilidad</Button></>} /><div className="metric-grid four"><MetricCard label="Movimientos hoy" value="32.890" icon={Activity} detail="+18,2% vs. promedio"/><MetricCard label="Entradas hoy" value="$184,3M" icon={ArrowDownLeft} detail="18.204 operaciones"/><MetricCard label="Salidas hoy" value="$96,7M" icon={ArrowUpRight} detail="14.686 operaciones" tone="blue"/><MetricCard label="En revisión" value="8" icon={AlertCircle} detail="$1,2M retenidos" tone="amber"/></div><Card title="Todos los movimientos" subtitle="Actividad de la cuenta madre y sus cuentas virtuales"><SearchFilters/><MovementTable/></Card></> }
function Withdrawals({ open }) {
  const [rows,setRows]=useState([{id:'RET-12042',user:'Juan Pérez',account:'CV-10021',amount:185400,status:'Pendiente',date:'Hoy, 10:38'},{id:'RET-12041',user:'Laura Méndez',account:'CV-10087',amount:850000,status:'Pendiente',date:'Hoy, 10:12'},{id:'RET-12039',user:'Sofía Castillo',account:'CV-10024',amount:56700,status:'Ejecutado',date:'Hoy, 09:41'},{id:'RET-12038',user:'Tomás Fuentes',account:'CV-10062',amount:240000,status:'Rechazado',date:'Hoy, 09:20'}])
  const change=(id,status)=>setRows(r=>r.map(x=>x.id===id?{...x,status}:x))
  return <><PageTitle eyebrow="Flujo de aprobación" title="Retiros y pagos" subtitle="Controla y aprueba salidas desde cada cuenta virtual." actions={<Button secondary icon={Settings}>Reglas de aprobación</Button>}/><div className="metric-grid four"><MetricCard label="Pendientes de aprobación" value="$42,6M" icon={ClipboardCheck} detail="4 solicitudes" tone="amber"/><MetricCard label="Ejecutados hoy" value="$96,7M" icon={CheckCircle2} detail="14.682 operaciones"/><MetricCard label="Tiempo promedio" value="3m 42s" icon={Activity} detail="Dentro del SLA" tone="blue"/><MetricCard label="Rechazados hoy" value="$1,4M" icon={X} detail="6 operaciones" tone="red"/></div><Card title="Solicitudes de retiro" subtitle="Acciones visuales de demo · no ejecutan pagos reales"><SearchFilters/><DataTable headers={['Solicitud','Usuario destino','Cuenta origen','Monto','Estado','Fecha solicitud','Acciones']}>{rows.map(r=><tr key={r.id}><td><code>{r.id}</code></td><td><div className="person"><Avatar name={r.user} small/><b>{r.user}</b></div></td><td>{r.account}</td><td><b>{money(r.amount)}</b></td><td><StatusBadge>{r.status}</StatusBadge></td><td className="muted">{r.date}</td><td><div className="row-actions">{r.status==='Pendiente'?<><button className="approve" onClick={()=>change(r.id,'Aprobado')}><Check size={14}/> Aprobar</button><button className="reject" onClick={()=>change(r.id,'Rechazado')}><X size={14}/></button></>:<button onClick={()=>open('trace')}>Trazabilidad</button>}</div></td></tr>)}</DataTable></Card></>
}
function Reconciliation() {
  const [pending,setPending]=useState(true)
  return <><PageTitle eyebrow="Cierre financiero" title="Conciliación" subtitle="Conecta cada movimiento de la cuenta madre con su cuenta virtual y destino final." actions={<Button icon={CheckCircle2} onClick={()=>setPending(false)}>Conciliar pendientes</Button>}/><div className="metric-grid four"><MetricCard label="Recaudación del día" value="$184,3M" icon={ArrowDownLeft} detail="100% registrado"/><MetricCard label="Retiros ejecutados" value="$96,7M" icon={ArrowUpRight} detail="14.682 operaciones" tone="blue"/><MetricCard label="Pendiente por conciliar" value={pending?'$4,8M':'$0'} icon={ClipboardCheck} detail={pending?'48 movimientos':'Todo conciliado'} tone="amber"/><MetricCard label="Cuentas con alerta" value={pending?'12':'3'} icon={AlertCircle} detail="Requieren revisión" tone="red"/></div><Card title="Ruta de conciliación" subtitle="Trazabilidad punta a punta"><Timeline compact/></Card><div className="two-col"><Card title="Progreso de conciliación" subtitle="Cierre diario de hoy"><div className="recon-ring"><div className="score-ring large"><b>{pending?'98,2':'100'}%</b><span>conciliado</span></div><div className="recon-detail"><span><i className="green-dot"/>Conciliado <b>{pending?'$276,2M':'$281,0M'}</b></span><span><i className="amber-dot"/>Pendiente <b>{pending?'$4,8M':'$0'}</b></span><span><i className="gray-dot"/>Alertas <b>{pending?'12':'3'} cuentas</b></span></div></div></Card><Card title="Pendientes prioritarios" subtitle="Movimientos que requieren atención"><div className="pending-list">{['Diferencia comisión ProntoPaga','Retiro Juan Pérez','Movimiento retenido Diego Morales'].map((x,i)=><div key={x}><span className={`severity s${i}`}/><div><b>{x}</b><small>{i===0?'OP-948166 · $128.000':i===1?'OP-948199 · $185.400':'OP-948151 · $120.000'}</small></div><StatusBadge>{pending?'Pendiente':'Conciliado'}</StatusBadge></div>)}</div></Card></div></>
}
const cardItems=[['Tarjeta Operaciones','Física','CV Proveedores','$12.000.000','$4.280.400','Activa','Felipe Torres'],['Tarjeta Retiros','Virtual','CV Retiros','$20.000.000','$8.620.000','Activa','Benja'],['Tarjeta Marketing','Virtual','CV Marketing','$8.000.000','$5.120.000','Activa','Camila Rojas'],['Tarjeta Proyecto USD','Virtual','CV Proyecto USD','USD 15.000','USD 2.840','Próximamente','Felipe Torres']]
function CardsView({open}) { return <><PageTitle eyebrow="Capa futura" title="Tarjetas" subtitle="Extensiones operativas asociadas a cuentas virtuales." actions={<Button icon={Plus} onClick={()=>open('card')}>Crear tarjeta</Button>}/><div className="concept-note"><CreditCard size={20}/><div><strong>Las tarjetas son una extensión operativa.</strong><p>Se construyen sobre las cuentas virtuales y no son el producto principal de Yol1 Business.</p></div></div><div className="cards-grid">{cardItems.map((c,i)=><div className={`payment-card pc${i}`} key={c[0]}><div className="pc-top"><span>Yol1 <b>Business</b></span><Zap size={19}/></div><small>{c[1]} · {c[2]}</small><h3>{c[0]}</h3><div className="pc-number">•••• &nbsp;•••• &nbsp;•••• &nbsp;{4192+i*117}</div><div className="pc-spend"><span><small>Gasto del mes</small><b>{c[4]}</b></span><span><small>Límite mensual</small><b>{c[3]}</b></span></div><div className="pc-bottom"><StatusBadge>{c[5]}</StatusBadge><span>{c[6]}</span></div></div>)}</div></> }
function Reports() { const pie=[{name:'Usuarios finales',value:340,color:'#80EF0C'},{name:'Recaudación',value:275,color:'#112E3C'},{name:'Operación',value:129,color:'#00D4AF'},{name:'Conciliación',value:101,color:'#A2A682'}];return <><PageTitle eyebrow="Inteligencia financiera" title="Reportes" subtitle="Una vista ejecutiva del desempeño de todas tus cuentas." actions={<Button icon={Download} onClick={()=>alert('Demo conceptual: el reporte no se descarga realmente.')}>Exportar reporte</Button>}/><div className="filters report-filters"><button><Filter size={15}/> Todas las cuentas <ChevronDown size={14}/></button><button>Últimos 6 meses <ChevronDown size={14}/></button><button>CLP <ChevronDown size={14}/></button></div><div className="two-col"><Card title="Entradas vs. salidas" subtitle="MM CLP por mes"><div className="chart"><ResponsiveContainer><BarChart data={chartData}><CartesianGrid stroke="#e5e2d8" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="entradas" fill="#80EF0C" radius={[5,5,0,0]}/><Bar dataKey="salidas" fill="#112E3C" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card title="Saldo por tipo de cuenta" subtitle="Distribución consolidada"><div className="pie-chart"><ResponsiveContainer><PieChart><Pie data={pie} innerRadius={65} outerRadius={95} dataKey="value">{pie.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="pie-legend">{pie.map(x=><span key={x.name}><i style={{background:x.color}}/>{x.name}<b>${x.value}M</b></span>)}</div></div></Card></div><div className="metric-grid four"><MetricCard label="Top usuario por saldo" value="$4,8M" icon={Users} detail="Valentina Soto"/><MetricCard label="Retiros aprobados" value="91,4%" icon={CheckCircle2} detail="+2,1 pts este mes"/><MetricCard label="Pendiente por conciliar" value="$4,8M" icon={ClipboardCheck} detail="1,8% del flujo" tone="amber"/><MetricCard label="Eficiencia operativa" value="94/100" icon={Activity} detail="+6 pts este mes" tone="blue"/></div></> }
function Permissions(){const rows=[['Benja','Administrador','$500.000.000','Activa'],['Felipe Torres','Finanzas','$100.000.000','Activa'],['Camila Rojas','Aprobador','$25.000.000','Activa'],['Diego Pérez','Visualizador','Sin aprobación','Activa'],['Contador externo','Contador externo','Sin aprobación','Pendiente']];return <><PageTitle eyebrow="Control de acceso" title="Usuarios y permisos" subtitle="Define quién puede ver, operar y aprobar en la cuenta empresa." actions={<Button icon={Plus}>Invitar usuario</Button>}/><Card title="Equipo ArenaPlay Demo SpA" subtitle="5 usuarios con acceso"><DataTable headers={['Usuario','Rol','Límite de aprobación','Estado','Permisos','']}>{rows.map(r=><tr key={r[0]}><td><div className="person"><Avatar name={r[0]} small/><b>{r[0]}</b></div></td><td><StatusBadge>{r[1]}</StatusBadge></td><td>{r[2]}</td><td><StatusBadge>{r[3]}</StatusBadge></td><td><div className="permission-dots"><i/><i/><i/><i className={r[1]==='Visualizador'?'off':''}/></div></td><td><button className="more"><MoreHorizontal size={18}/></button></td></tr>)}</DataTable></Card></>}
const integrations=[['ProntoPaga','Infraestructura transaccional','Conectado','PP'],['Banco BICE','Estructura inicial de cuentas','Conectado','BI'],['ILP','Habilitador futuro de tarjetas','Próximamente','IL'],['SII','Integración tributaria futura','Futura','SII'],['API Yol1','Conexión programática segura','Próximamente','API'],['Webhooks','Eventos operativos en tiempo real','Próximamente','WH']]
function Integrations(){return <><PageTitle eyebrow="Ecosistema conectado" title="Integraciones" subtitle="Infraestructura que habilita la operación visible de Yol1 Business." actions={<Button secondary icon={ReceiptText}>Documentación API</Button>}/><div className="integration-highlight"><div className="yol1-orbit">Yol1 <b>Business</b></div><p>El producto visible para empresas</p><div className="orbit-lines"><span>Infraestructura</span><span>Cuentas</span><span>Tarjetas futuras</span></div></div><div className="integration-grid">{integrations.map((x,i)=><Card key={x[0]} className="integration-card"><div className={`integration-logo il${i}`}>{x[3]}</div><h3>{x[0]}</h3><p>{x[1]}</p><StatusBadge>{x[2]}</StatusBadge><button className="text-action">Ver detalle <ArrowRight size={14}/></button></Card>)}</div></>}
function SettingsView(){const items=[[Building2,'Datos de empresa','Razón social, RUT e información corporativa'],[ReceiptText,'Documentación','Documentos legales y operativos'],[ShieldCheck,'Seguridad','Autenticación y políticas de acceso'],[Activity,'Límites operativos','Montos y reglas de operación'],[ClipboardCheck,'Auditoría','Registro de eventos y acciones'],[CircleDollarSign,'Preferencias de moneda','CLP principal, USD y EUR'],[Landmark,'Cuentas vinculadas','Banco BICE · cuenta terminada en 0182']];return <><PageTitle eyebrow="Administración" title="Configuración" subtitle="Preferencias y controles de ArenaPlay Demo SpA."/><div className="settings-grid">{items.map(([Icon,title,sub])=><button key={title} className="settings-item"><span><Icon size={19}/></span><div><b>{title}</b><small>{sub}</small></div><ChevronRight size={18}/></button>)}</div></>}

function Sidebar({active,setActive,mobile,setMobile}) { return <aside className={`sidebar ${mobile?'mobile-open':''}`}><div className="brand"><img src={yol1Logo} alt="Yol1 Business"/><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="company-switch"><div className="company-icon">AP</div><div><b>ArenaPlay Demo SpA</b><span>Cuenta empresa · CLP</span></div><ChevronDown size={15}/></div><nav><span className="nav-label">OPERACIÓN</span>{nav.slice(0,8).map(([name,Icon])=><button key={name} className={active===name?'active':''} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={17}/><span>{name}</span>{name==='Retiros y pagos'&&<em>4</em>}{name==='Conciliación'&&<em>12</em>}</button>)}<span className="nav-label">ADMINISTRACIÓN</span>{nav.slice(8).map(([name,Icon])=><button key={name} className={active===name?'active':''} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={17}/><span>{name}</span></button>)}</nav><div className="sidebar-footer"><div className="demo-tag"><Sparkles size={15}/><span><b>Demo conceptual</b><small>No procesa datos reales</small></span></div><div className="profile"><Avatar name="Benja" small/><div><b>Benja</b><span>Administrador</span></div><MoreHorizontal size={17}/></div></div></aside> }
function Header({setMobile}) { return <header><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div className="global-search"><Search size={17}/><span>Buscar transacciones o iniciar una acción</span><kbd>⌘ K</kbd></div><div className="header-right"><div className="system-ok"><span/> Sistemas operativos</div><button className="icon-btn"><Bell size={18}/><i/></button><Avatar name="Benja" small/></div></header> }
function App() {
  const [active,setActive]=useState('Vista general'), [modal,setModal]=useState(null), [mobile,setMobile]=useState(false)
  const props={open:setModal,navigate:setActive}
  const views={'Vista general':<Overview {...props}/>, 'Cuentas virtuales':<VirtualAccounts {...props}/>, 'Usuarios finales':<UsersView {...props}/>, 'Movimientos':<MovementsView {...props}/>, 'Retiros y pagos':<Withdrawals {...props}/>, 'Conciliación':<Reconciliation {...props}/>, 'Tarjetas':<CardsView {...props}/>, 'Reportes':<Reports {...props}/>, 'Usuarios y permisos':<Permissions {...props}/>, 'Integraciones':<Integrations {...props}/>, 'Configuración':<SettingsView {...props}/>}
  return <div className="app"><Sidebar active={active} setActive={setActive} mobile={mobile} setMobile={setMobile}/><div className="main"><Header setMobile={setMobile}/><main>{views[active]}</main></div>{modal&&<Modal type={modal} onClose={()=>setModal(null)}/>}</div>
}
export default App
